for (f in list.files("R", full.names = TRUE)) source(f)
source("dev/demo_data.R")
sp <- nesting_spec(dat, response ~ chord_type * inversion + training,
                   nests = "inversion %in% chord_type")
print(sp)
cat("cell levels:", paste(sp$cell_levels, collapse = " "), "\n")
A <- effect_basis(sp)
cat("A:", nrow(A), "x", ncol(A), " rank", qr(A)$rank, "\n")
cat("effects:", paste(colnames(A), collapse = " | "), "\n")
tr <- translation(sp); print(tr)
m <- lm(cell_formula(sp), data = sp$data)
cat("cell fit: rank", m$rank, " NA coefs", sum(is.na(coef(m))), "\n")
m_chain <- lm(cell_formula(sp, "effects"), data = sp$data)
cat("effects fit:", paste(deparse(formula(m_chain)), collapse=""), "\n")
cat("logLik equal:", isTRUE(all.equal(logLik(m), logLik(m_chain))), "\n")
## estimand in original labels from the cell fit
suppressPackageStartupMessages(library(marginaleffects))
e <- avg_predictions(m, newdata = sp$data, by = "chord_type", hypothesis = "pairwise")
print(as.data.frame(e)[, 1:3])
